#server port of Eureka server
server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/