server:
  port: 9006

spring:
  application:
    name: USER-SERVER

cloud:
  aws:
    credentials:
      access-key: AKIATJRIZDIJDJP73TQC
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: usersdocumentstorage


  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:${EUREKA_PORT:8761}/eureka/
